from .gas_sensor import GasSensorSettings
from .fire_sensor import FireSensorSettings
from .gerkon import GerkonSettings
from .socket import SocketSettings
from .socket_button import SocketButtonSettings
from .vibration_sensor import VibrationSensorSettings
from .water_sensor import WaterSensorSettings
from .invertor import InvertorSettings
from .wifi_lock import WiFiLockSettings
from .socket_3x import Socket3xSettings
from .tuvak import TuvakSettings